### ISSUE TITLE
Friendly Paull request

### ISSUE THREAD

**Issue by al75an** [FireFather/Zentropy#2]
Thank you for this cool chess gui.
I am sorry, I couldn't create a pull request, this is why I created an Issue.
Could you please ad Analyzing mode to the Gui (to analyze chess games)

**Comment by FireFather** [comment]
From the top menu bar, choose:
Time,
Control,
and
Infinite
to analyze games

The engine(s) will analyze until stopped

**Comment by al75an** [comment]
I meant to open a multigames pgn in Zentropy and choose the game and position to Analyze.
Right now the only option available for pgn is to paste 1 game at the time

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by FireFather** [comment]
I'll consider PGN read support for the next release
Thanks for the suggestion...
