### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Krzychumag** [FireFather/Zentropy#6]
I have a request and a question. Can you take a look at my question at the link https://talkchess.com/forum3/viewtopic.php?f=2&t=82371&sid=552559d1cc356e34fdeb3b607c4014b9 and answer it. Thank you in advance.

Krzysztof

**Comment by FireFather** [comment]
See menu option
Book
Options
Create

Here you can enter the name of the pgn to import
and the book depth (for ex: if you enter 8...the book lines will use the 1st 8 moves of each game).
